version: '3'

services:
    app:
        build: .
        ports:
            - 8080:80
        command: flask run --host=0.0.0.0 --port=80
#        command: gunicorn -b 0.0.0.0:80 manage:app
        volumes:
            - ./:/app:cached
        environment:
            - FLASK_ENV=development
