[tool.poetry]
name = "masterofgames"
version = "2.1.0"
description = "Helps you get all the achievements from your games"
authors = ["Saphyel"]
license = "MIT"

[tool.poetry.dependencies]
appdirs = "^1.4.4"
Flask = {extras = ["async"], version = "^2.0.2"}
gunicorn = {extras = ["eventlet"], version = "^20.1.0"}
httpx = "^0.19.0"
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pytest = "^6.2.5"
pytest-asyncio = "^0.15.1"

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'

[tool.pytest.ini_options]
cache_dir = "/tmp/cache"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
