[tool.poetry]
name = "masterofgames"
version = "2.0.0"
description = "Helps you get all the achievements from your games"
authors = ["Saphyel"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"
flask = "^1.1.2"
python-dotenv = "^0.14.0"
gunicorn = "^20.0.4"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
flake8 = "^3.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
