[tool.poetry]
name = "masterofgames"
version = "2.0.1"
description = "Helps you get all the achievements from your games"
authors = ["Saphyel"]
license = "MIT"

[tool.poetry.dependencies]
appdirs = "^1.4.4"
flask = "^2.0.1"
gunicorn = "^20.1.0"
python = "^3.9"
requests = "^2.25.0"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pytest = "^6.2.5"

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'

[tool.pytest.ini_options]
cache_dir = "/tmp/cache"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
