[tool.poetry]
name = "masterofgames"
version = "2.0.1"
description = "Helps you get all the achievements from your games"
authors = ["Saphyel"]
license = "MIT"

[tool.poetry.dependencies]
flask = "^1.1.2"
gunicorn = "^20.0.4"
python = "^3.8"
python-dotenv = "^0.14.0"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.1.1"

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
