[project]
name = "masterofgames"
version = "3.0"
description = "Helps you get all the achievements from your games"
license = {text = "OSL-3.0"}
authors = [{name = "Saphyel"}]

requires-python = ">=3.11"
dependencies = [
    "Flask[async]==2.3.2",
    "gunicorn[eventlet]==20.1.0",
    "httpx==0.24.1",
    "uvicorn==0.22.0",
]
[project.optional-dependencies]
test = [
    "black==23.3.0",
    "pytest==7.3.1",
    "pytest-asyncio==0.21.0"
]

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'

[tool.pytest.ini_options]
cache_dir = "/tmp/cache"

[build-system]
requires = ["setuptools>=63.0"]
build-backend = "setuptools.build_meta"
