name: Python application

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build -t local .
    - name: Install dev tools
      run: |
        docker run --name app local pip install .[test]
        docker commit app app
    - name: Check code style
      run: docker run app black --check .
    - name: Test with pytest
      run: docker run app pytest
